version: '3'

services:

  #importing Dockerfile configurations
  liberty-server:
    build: .
    ports: 
      - "9080:9080"
      - "9443:9443"
    depends_on: 
      - mysql-server

  #MySQL Database Server Configurations
  mysql-server:
    image: mysql:8.0.20
    command: mysqld --user=root
    environment:
      MYSQL_ROOT_PASSWORD: wissam
      MYSQL_DATABASE: rateme
    ports:
    - 3306
     # - "3308:3306"
    volumes:
        - ./InitScrips/:/docker-entrypoint-initdb.d/:rw
      
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
  
  
  #Openliberty Server Configurations
 # liberty-server:
 #   image: open-liberty:microProfile3
  #  ports: 
  #    - "9080:9080"
  #    - "9443:9443"
  #  volumes: 
 #     - ./target/DemoNoteListMicroprofile.war:/opt/ol
  #  depends_on: 
 #     - mysql-server

     